AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

  Sample SAM Template 

Globals:
  Function:
    Timeout: 900
    MemorySize: 2048
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        DB_RDS_HOST: !Ref DbRdsHost

  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      MaxAge: 3000
      AllowCredentials: "'true'"
Parameters:
  Region:
    Type: String
    Default: ap-northeast-1
  env:
    Type: String
    Default: stg
    AllowedValues:
      - dev
      - stg
      - p
  SecurityGroupIds:
    Type: String
    Description: "Comma-delimited list of security group IDs"
  SubnetIds:
    Type: String
    Description: "Comma-delimited list of subnet IDs"
  RegionName:
    Type: String
    NoEcho: true

Resources:
  # API GATEWAY
  TestOCRApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'test-ocr-api'
      StageName: v1
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        MaxAge: 3000
        AllowCredentials: "'true'"
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseTemplates:
            application/json: '{"message": "Unauthorized"}'
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Requested-With'"
              Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        EXPIRED_TOKEN:
          StatusCode: 401
          ResponseTemplates:
            application/json: '{"message": "Token expired"}'
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Requested-With'"
              Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Requested-With'"
              Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Requested-With'"
              Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"

  # LAMBDA FUNCTIONS
  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'test-ocr-api-health-check'
      PackageType: Image
      ImageUri: 529928146857.dkr.ecr.us-east-1.amazonaws.com/ocr:latest
      Policies:
        - PolicyName: AllowEcrPull
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                # Giới hạn tới repo cụ thể; đổi nếu muốn nhiều repo hoặc cross-account
                Resource: "arn:aws:ecr:us-east-1:529928146857:repository/ocr"
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - "sg-038d7ff42a9d98eeb"
        SubnetIds:
          - "subnet-0003d6450c89b2f7d"
      # Layers:
      #   - !Ref CommonApstApiteLayer
      Events:
        DatasetJobStatus:
          Type: Api
          Properties:
            Path: /health
            Method: get
            RestApiId: !Ref TestOCRApi
  # CommonApstApiteLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: common-layer
  #     Description: A layer containing common code
  #     ContentUri: src/layer/
  #     CompatibleRuntimes:
  #       - python3.12
  #     LicenseInfo: MIT

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${env}-api.execute-api.${AWS::Region}.amazonaws.com/Stage/"
